fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    augeasproviders_apache:
      repo: git://github.com/hercules-team/augeasproviders_apache.git
    augeasproviders_grub:
      repo: git://github.com/hercules-team/augeasproviders_grub.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    augeasproviders_ssh:
      repo: git://github.com/hercules-team/augeasproviders_ssh.git
    augeasproviders_sysctl:
      repo: git://github.com/hercules-team/augeasproviders_sysctl.git
    augeasproviders_syslog:
      repo: git://github.com/hercules-team/augeasproviders_syslog.git
  symlinks:
    "augeasproviders": "#{source_dir}"
