fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    augeasproviders_shellvar:
      repo: git@github.com:hercules-team/augeasproviders_shellvar.git
  symlinks:
    "augeasproviders": "#{source_dir}"
